{
  "swagger": "2.0",
  "schemes": [
    "https"
  ],
  "host": "api.icons8.com",
  "basePath": "/",
  "info": {
    "description": "Icons8 API allows us to search and obtain [our icons](https://icons8.com/web-app).\n\nYou're welcome to use our icons to extend the functionality of your web and mobile applications, website templates, and even tattoos.\n\n![Tattoos](https://cdn.rawgit.com/icons8/api-docs/cff6fdf0/tattoos.svg)\n\n## Usage Examples\n\nSome examples of what you can do with our icons:\n\n* **Template customization.** This way, [Canva](https://www.canva.com/) uses our icons to customize their layouts.\n\n* **Graphics and text editors.** [Gravit](https://gravit.io/) allows to insert our icons into the mockups.\n\n* **Any application with customization.** [TimeTune](http://timetune.center/) uses our icons to customize the activities.\n\n## Getting Started\n\nTo get started, please [contact us](https://icons8.com/contact) to obtain an API key.\n\n## Pricing\n\nOur API license starts at $100/month.",
    "title": "Icons8",
    "version": "1.0.0",
    "x-apisguru-categories": [
      "media"
    ],
    "x-logo": {
      "url": "https://api.apis.guru/v2/cache/logo/https_pbs.twimg.com_profile_images_837777358883065857_YCw6bjtl_400x400.jpg"
    },
    "x-origin": [
      {
        "converter": {
          "url": "https://github.com/lucybot/api-spec-converter",
          "version": "2.5.0"
        },
        "format": "apiBlueprint",
        "url": "http://docs.icons8.apiary.io/api-description-document",
        "version": "1A"
      }
    ],
    "x-preferred": true,
    "x-providerName": "icons8.com"
  },
  "produces": [
    "application/json"
  ],
  "paths": {
    "/api/iconsets/v3/categories?platform={platform}&language={language}": {
      "get": {
        "description": "The operation will not return the categories that have less than 10 icons.\nWe need it to test the categories without showing garbage on the production website.",
        "parameters": [
          {
            "description": "the platform that we are searching icons for",
            "enum": [
              "ios7",
              "win8",
              "win10",
              "android",
              "androidL",
              "color",
              "office"
            ],
            "in": "path",
            "name": "platform",
            "required": true,
            "type": "string"
          },
          {
            "description": "the language code to get localized result",
            "enum": [
              "en-US",
              "fr-FR",
              "de-DE",
              "it-IT",
              "pt-BR",
              "pl-PL",
              "ru-RU",
              "es-ES"
            ],
            "in": "path",
            "name": "language",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "parameters": {
                  "language": "",
                  "platform": ""
                },
                "result": {
                  "categories": [
                    {
                      "category_code": "",
                      "category_name": "",
                      "subcategory": [
                        {
                          "icons": [
                            {
                              "common_icon_id": 0,
                              "created": "",
                              "features": {
                                "bitmap": 0,
                                "nolink": 0,
                                "vector": 0
                              },
                              "id": 0,
                              "name": "",
                              "platform_code": "",
                              "svg": "",
                              "url": ""
                            }
                          ],
                          "subcategory_code": "",
                          "subcategory_name": ""
                        }
                      ]
                    },
                    {
                      "api_code": "Alphabet",
                      "category_code": "",
                      "category_name": "",
                      "name": "Alphabet",
                      "subcategory": [
                        {
                          "icons": [
                            {
                              "common_icon_id": 0,
                              "created": "",
                              "features": {
                                "bitmap": 0,
                                "nolink": 0,
                                "vector": 0
                              },
                              "id": 0,
                              "name": "",
                              "platform_code": "",
                              "svg": "",
                              "url": ""
                            }
                          ],
                          "subcategory_code": "",
                          "subcategory_name": ""
                        }
                      ]
                    },
                    {
                      "api_code": "Very_Basic",
                      "category_code": "",
                      "category_name": "",
                      "name": "Very Basic",
                      "subcategory": [
                        {
                          "icons": [
                            {
                              "common_icon_id": 0,
                              "created": "",
                              "features": {
                                "bitmap": 0,
                                "nolink": 0,
                                "vector": 0
                              },
                              "id": 0,
                              "name": "",
                              "platform_code": "",
                              "svg": "",
                              "url": ""
                            }
                          ],
                          "subcategory_code": "",
                          "subcategory_name": ""
                        }
                      ]
                    },
                    {
                      "api_code": "Photo_Video",
                      "category_code": "",
                      "category_name": "",
                      "name": "Photo and Video",
                      "subcategory": [
                        {
                          "icons": [
                            {
                              "common_icon_id": 0,
                              "created": "",
                              "features": {
                                "bitmap": 0,
                                "nolink": 0,
                                "vector": 0
                              },
                              "id": 0,
                              "name": "",
                              "platform_code": "",
                              "svg": "",
                              "url": ""
                            }
                          ],
                          "subcategory_code": "",
                          "subcategory_name": ""
                        }
                      ]
                    }
                  ]
                }
              }
            },
            "headers": {},
            "schema": {
              "properties": {
                "parameters": {
                  "description": "copy of the input parameters from the request",
                  "properties": {
                    "language": {
                      "type": "string"
                    },
                    "platform": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                },
                "result": {
                  "description": "the result of operation",
                  "properties": {
                    "categories": {
                      "items": {},
                      "type": "array"
                    }
                  },
                  "type": "object"
                }
              },
              "type": "object"
            }
          }
        },
        "summary": "Categories",
        "tags": []
      }
    },
    "/api/iconsets/v3/category?category={category}&subcategory={subcategory}&amount={amount}&offset={offset}&platform={platform}&language={language}": {
      "get": {
        "description": "",
        "parameters": [
          {
            "description": "the code of category",
            "in": "path",
            "name": "category",
            "required": true,
            "type": "string"
          },
          {
            "description": "the code of subcategory",
            "in": "path",
            "name": "subcategory",
            "required": true,
            "type": "string"
          },
          {
            "default": 25,
            "description": "the maximum number of icons which you'd like to receive",
            "in": "path",
            "name": "amount",
            "required": true,
            "type": "number"
          },
          {
            "description": "the offset from the first received result",
            "in": "path",
            "name": "offset",
            "required": true,
            "type": "number"
          },
          {
            "description": "the style of the icons",
            "enum": [
              "ios7",
              "win8",
              "win10",
              "android",
              "androidL",
              "color",
              "office"
            ],
            "in": "path",
            "name": "platform",
            "required": true,
            "type": "string"
          },
          {
            "description": "the language code to get localized result",
            "enum": [
              "en-US",
              "fr-FR",
              "de-DE",
              "it-IT",
              "pt-BR",
              "pl-PL",
              "ru-RU",
              "es-ES"
            ],
            "in": "path",
            "name": "language",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "parameters": {
                  "amount": 0,
                  "category": "",
                  "language": "",
                  "offset": "",
                  "platform": "",
                  "subcategory": ""
                },
                "result": {
                  "category": [
                    {
                      "category_code": "",
                      "category_name": "",
                      "subcategory": [
                        {
                          "icons": [
                            {
                              "common_icon_id": 0,
                              "created": "",
                              "features": {
                                "bitmap": 0,
                                "nolink": 0,
                                "vector": 0
                              },
                              "id": 0,
                              "name": "",
                              "platform_code": "",
                              "svg": "",
                              "url": ""
                            }
                          ],
                          "subcategory_code": "",
                          "subcategory_name": ""
                        }
                      ]
                    },
                    {
                      "category": "Very Basic",
                      "common_icon_id": "72",
                      "created": "2015-05-21T05:28:59+00:00",
                      "features": {
                        "bitmap": "1",
                        "nolink": "1",
                        "vector": "1"
                      },
                      "id": "12229",
                      "name": "Home",
                      "platform_code": "color",
                      "share": {
                        "png": [
                          {
                            "link": "https://maxcdn.icons8.com/Share/google/h/home.png"
                          },
                          {
                            "link": "https://maxcdn.icons8.com/Share/twitter/h/home.png",
                            "type": "twitter"
                          },
                          {
                            "link": "https://maxcdn.icons8.com/Share/social/h/home.png",
                            "type": "social"
                          }
                        ],
                        "url": "http://ic8.link/12229"
                      },
                      "subcategory": {
                        "api_code": "website_sections",
                        "name": "Website Sections"
                      },
                      "svg": "/* Plain SVG content here */",
                      "url": "/web-app/12229/home",
                      "vector": {
                        "eps": "absolute/private/url/to/home.eps",
                        "pdf": "absolute/private/url/to/home.pdf",
                        "svg-editable": "absolute/private/url/to/original/home.svg",
                        "svg-simplified": "absolute/private/url/to/simplified/home.svg"
                      }
                    }
                  ]
                }
              }
            },
            "headers": {},
            "schema": {
              "properties": {
                "parameters": {
                  "description": "copy of the input parameters from the request",
                  "properties": {
                    "amount": {
                      "type": "number"
                    },
                    "category": {
                      "type": "string"
                    },
                    "language": {
                      "type": "string"
                    },
                    "offset": {
                      "type": "string"
                    },
                    "platform": {
                      "type": "string"
                    },
                    "subcategory": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                },
                "result": {
                  "description": "the result of operation",
                  "properties": {
                    "category": {
                      "items": {},
                      "type": "array"
                    }
                  },
                  "type": "object"
                }
              },
              "type": "object"
            }
          }
        },
        "summary": "By Category",
        "tags": []
      }
    },
    "/api/iconsets/v3/latest?term={term}&amount={amount}&offset={offset}&platform={platform}&language={language}": {
      "get": {
        "description": "",
        "parameters": [
          {
            "default": 25,
            "description": "the maximum number of icons which you'd like to receive",
            "in": "path",
            "name": "amount",
            "required": true,
            "type": "number"
          },
          {
            "description": "the offset from the first received result",
            "in": "path",
            "name": "offset",
            "required": true,
            "type": "number"
          },
          {
            "description": "the style of the icons",
            "enum": [
              "ios7",
              "win8",
              "win10",
              "android",
              "androidL",
              "color",
              "office"
            ],
            "in": "path",
            "name": "platform",
            "required": true,
            "type": "string"
          },
          {
            "description": "the language code to get localized result",
            "enum": [
              "en-US",
              "fr-FR",
              "de-DE",
              "it-IT",
              "pt-BR",
              "pl-PL",
              "ru-RU",
              "es-ES"
            ],
            "in": "path",
            "name": "language",
            "required": true,
            "type": "string"
          },
          {
            "in": "path",
            "name": "term",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "parameters": {
                  "amount": 0,
                  "language": "",
                  "offset": "",
                  "platform": "",
                  "term": ""
                },
                "result": {
                  "latest": [
                    {
                      "common_icon_id": 0,
                      "created": "color",
                      "features": {
                        "bitmap": 0,
                        "nolink": 0,
                        "vector": 0
                      },
                      "id": 0,
                      "name": "",
                      "platform_code": "",
                      "share": {
                        "png": [
                          {
                            "link": ""
                          }
                        ],
                        "url": ""
                      },
                      "subcategory": {
                        "api_code": "",
                        "name": ""
                      },
                      "svg": "",
                      "vector": {
                        "eps": "",
                        "pdf": "",
                        "svg-simplified": ""
                      }
                    },
                    {
                      "common_icon_id": "72",
                      "created": "2015-05-21T05:28:59+00:00",
                      "features": {
                        "bitmap": "1",
                        "nolink": "1",
                        "vector": "1"
                      },
                      "id": "12229",
                      "name": "Home",
                      "platform_code": "color",
                      "share": {
                        "png": [
                          {
                            "link": "https://maxcdn.icons8.com/Share/google/h/home.png"
                          },
                          {
                            "link": "https://maxcdn.icons8.com/Share/twitter/h/home.png",
                            "type": "twitter"
                          },
                          {
                            "link": "https://maxcdn.icons8.com/Share/social/h/home.png",
                            "type": "social"
                          }
                        ],
                        "url": "http://ic8.link/12229"
                      },
                      "subcategory": {
                        "api_code": "",
                        "name": ""
                      },
                      "svg": "",
                      "url": "/web-app/12229/home",
                      "vector": {
                        "eps": "",
                        "pdf": "",
                        "svg-simplified": ""
                      }
                    }
                  ]
                }
              }
            },
            "headers": {},
            "schema": {
              "properties": {
                "parameters": {
                  "description": "copy of the input parameters from the request",
                  "properties": {
                    "amount": {
                      "type": "number"
                    },
                    "language": {
                      "type": "string"
                    },
                    "offset": {
                      "type": "string"
                    },
                    "platform": {
                      "type": "string"
                    },
                    "term": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                },
                "result": {
                  "description": "the result of operation",
                  "properties": {
                    "latest": {
                      "items": {},
                      "type": "array"
                    }
                  },
                  "type": "object"
                }
              },
              "type": "object"
            }
          }
        },
        "summary": "Latest",
        "tags": []
      }
    },
    "/api/iconsets/v3/search?term={term}&amount={amount}&offset={offset}&platform={platform}&language={language}&exact_amount={exact_amount}": {
      "get": {
        "description": "",
        "parameters": [
          {
            "description": "the name or tag of the icon or any other phrase.\ne.g. use \"@home\" to find icons with the tag \"home\" and \"=home\" to find icons with the name \"home\"\n",
            "in": "path",
            "name": "term",
            "required": true,
            "type": "string"
          },
          {
            "default": 25,
            "description": "the maximum number of icons which you'd like to receive (will be multiplied by platforms count, if you didn't specify the platform and didn't set the 'exact_amount' parameter)",
            "in": "path",
            "name": "amount",
            "required": true,
            "type": "number"
          },
          {
            "description": "set it to 'true' if you'd like to receive the exact amount of icons, not multiplied by platforms count",
            "in": "path",
            "name": "exact_amount",
            "required": true,
            "type": "boolean"
          },
          {
            "description": "the offset from the first received result",
            "in": "path",
            "name": "offset",
            "required": true,
            "type": "number"
          },
          {
            "description": "the style of the icons",
            "enum": [
              "ios7",
              "win8",
              "win10",
              "android",
              "androidL",
              "color",
              "office"
            ],
            "in": "path",
            "name": "platform",
            "required": true,
            "type": "string"
          },
          {
            "description": "the language code to get localized result",
            "enum": [
              "en-US",
              "fr-FR",
              "de-DE",
              "it-IT",
              "pt-BR",
              "pl-PL",
              "ru-RU",
              "es-ES"
            ],
            "in": "path",
            "name": "language",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "parameters": {
                  "amount": 0,
                  "language": "",
                  "offset": "",
                  "platform": "",
                  "term": ""
                },
                "result": {
                  "search": [
                    {
                      "common_icon_id": 0,
                      "created": "color",
                      "features": {
                        "bitmap": 0,
                        "nolink": 0,
                        "vector": 0
                      },
                      "id": 0,
                      "name": "",
                      "platform_code": "",
                      "share": {
                        "png": [
                          {
                            "link": ""
                          }
                        ],
                        "url": ""
                      },
                      "subcategory": {
                        "api_code": "",
                        "name": ""
                      },
                      "svg": "",
                      "vector": {
                        "eps": "",
                        "pdf": "",
                        "svg-simplified": ""
                      }
                    },
                    {
                      "category": "Very Basic",
                      "common_icon_id": "72",
                      "created": "2015-05-21T05:28:59+00:00",
                      "features": {
                        "bitmap": "1",
                        "nolink": "1",
                        "vector": "1"
                      },
                      "id": "12229",
                      "name": "Home",
                      "platform_code": "color",
                      "share": {
                        "png": [
                          {
                            "link": "https://maxcdn.icons8.com/Share/google/h/home.png"
                          },
                          {
                            "link": "https://maxcdn.icons8.com/Share/twitter/h/home.png",
                            "type": "twitter"
                          },
                          {
                            "link": "https://maxcdn.icons8.com/Share/social/h/home.png",
                            "type": "social"
                          }
                        ],
                        "url": "http://ic8.link/12229"
                      },
                      "subcategory": {
                        "api_code": "website_sections",
                        "name": "Website Sections"
                      },
                      "svg": "/* Plain SVG content here */",
                      "url": "/web-app/12229/home",
                      "vector": {
                        "eps": "absolute/private/url/to/home.eps",
                        "pdf": "absolute/private/url/to/home.pdf",
                        "svg-editable": "absolute/private/url/to/original/home.svg",
                        "svg-simplified": "absolute/private/url/to/simplified/home.svg"
                      }
                    }
                  ]
                }
              }
            },
            "headers": {},
            "schema": {
              "properties": {
                "parameters": {
                  "description": "copy of the input parameters from the request",
                  "properties": {
                    "amount": {
                      "type": "number"
                    },
                    "language": {
                      "type": "string"
                    },
                    "offset": {
                      "type": "string"
                    },
                    "platform": {
                      "type": "string"
                    },
                    "term": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                },
                "result": {
                  "description": "the result of operation",
                  "properties": {
                    "search": {
                      "items": {},
                      "type": "array"
                    }
                  },
                  "type": "object"
                }
              },
              "type": "object"
            }
          }
        },
        "summary": "By Keyword",
        "tags": []
      }
    },
    "/api/iconsets/v3/total?since={since}": {
      "get": {
        "description": "",
        "parameters": [
          {
            "description": "the optional date to calculate the total number of icons that were created after it.\nIt should be in format \"four year digits - dash - two month number digits - dash - two day number digits. For example 2014-12-31 means \"31th of December, 2014\".\n",
            "in": "path",
            "name": "since",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "parameters": {
                  "since": ""
                },
                "result": {
                  "total": [
                    {
                      "api_code": "ios7",
                      "name": "",
                      "total": 0
                    },
                    {
                      "api_code": "win8",
                      "name": "Windows 8/Metro",
                      "total": "802"
                    },
                    {
                      "api_code": "ios7",
                      "name": "iPhone/iOS 7",
                      "total": "7379"
                    }
                  ]
                }
              }
            },
            "headers": {},
            "schema": {
              "properties": {
                "parameters": {
                  "description": "copy of the input parameters from the request",
                  "properties": {
                    "since": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                },
                "result": {
                  "description": "the result of operation",
                  "properties": {
                    "total": {
                      "items": {},
                      "type": "array"
                    }
                  },
                  "type": "object"
                }
              },
              "type": "object"
            }
          }
        },
        "summary": "Totals",
        "tags": []
      }
    },
    "/api/task/web-font/collection": {
      "post": {
        "description": "",
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "schema": {
              "properties": {
                "auth": {
                  "properties": {
                    "hash": {
                      "description": "Authorization hash",
                      "type": "string"
                    }
                  },
                  "required": [
                    "hash"
                  ],
                  "type": "object"
                },
                "task": {
                  "properties": {
                    "arguments": {
                      "properties": {
                        "collection": {
                          "description": "collection identifier",
                          "type": "string"
                        },
                        "css_prefix": {
                          "default": "icons8",
                          "description": "prefix for CSS rules, used to generate LESS/SCSS",
                          "type": "string"
                        },
                        "css_rules_case": {
                          "default": "lowercase",
                          "description": "glyph names conversion rule",
                          "enum": [
                            "lowercase",
                            "as_is"
                          ],
                          "type": "string"
                        },
                        "css_selector": {
                          "default": ".icons8-{{glyph}}",
                          "description": "template for glyph selector; placeholder {{glyph}} will be replaced with glyph names",
                          "type": "string"
                        },
                        "font_name": {
                          "default": "font_icons8",
                          "description": "name of iconic webfont",
                          "type": "string"
                        }
                      },
                      "required": [
                        "collection",
                        "font_name"
                      ],
                      "type": "object"
                    }
                  },
                  "type": "object"
                }
              },
              "type": "object"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "messages": [
                  {
                    "code": "paid_feature",
                    "description": "Icons \"dog\", \"cat\" and 5 more were excluded"
                  },
                  {
                    "code": "not_possible",
                    "description": "Icons \"dog-color\" and \"cat-color\" were excluded"
                  }
                ],
                "result": {
                  "description": "",
                  "id": "abc-def",
                  "results": {
                    "zip": "https://st.icons8.com/zip/abc-def/icons8-font.zip"
                  },
                  "status": "complete",
                  "type": "create_web_font"
                }
              }
            },
            "headers": {},
            "schema": {
              "properties": {
                "messages": {
                  "items": {},
                  "type": "array"
                },
                "result": {
                  "properties": {
                    "description": {
                      "description": "human readable description",
                      "type": "string"
                    },
                    "id": {
                      "description": "task identifier",
                      "type": "string"
                    },
                    "results": {
                      "properties": {
                        "zip": {
                          "type": "string"
                        }
                      },
                      "type": "object"
                    },
                    "status": {
                      "description": "task status",
                      "type": "string"
                    },
                    "type": {
                      "description": "task type",
                      "type": "string"
                    }
                  },
                  "required": [
                    "id",
                    "type",
                    "status"
                  ],
                  "type": "object"
                }
              },
              "type": "object"
            }
          }
        },
        "summary": "From a Collection",
        "tags": []
      }
    },
    "/api/task/web-font/icons": {
      "post": {
        "description": "",
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "schema": {
              "properties": {
                "auth": {
                  "properties": {
                    "hash": {
                      "description": "Authorization hash",
                      "type": "string"
                    }
                  },
                  "required": [
                    "hash"
                  ],
                  "type": "object"
                },
                "task": {
                  "properties": {
                    "arguments": {
                      "properties": {
                        "collection": {
                          "description": "collection identifier",
                          "type": "string"
                        },
                        "css_prefix": {
                          "default": "icons8",
                          "description": "prefix for CSS rules, used to generate LESS/SCSS",
                          "type": "string"
                        },
                        "css_rules_case": {
                          "default": "lowercase",
                          "description": "glyph names conversion rule",
                          "enum": [
                            "lowercase",
                            "as_is"
                          ],
                          "type": "string"
                        },
                        "css_selector": {
                          "default": ".icons8-{{glyph}}",
                          "description": "template for glyph selector; placeholder {{glyph}} will be replaced with glyph names",
                          "type": "string"
                        },
                        "font_name": {
                          "default": "font_icons8",
                          "description": "name of iconic webfont",
                          "type": "string"
                        }
                      },
                      "required": [
                        "collection",
                        "font_name"
                      ],
                      "type": "object"
                    }
                  },
                  "type": "object"
                }
              },
              "type": "object"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "messages": [
                  {
                    "code": "paid_feature",
                    "description": "Icons \"dog\", \"cat\" and 5 more were excluded"
                  },
                  {
                    "code": "not_possible",
                    "description": "Icons \"dog-color\" and \"cat-color\" were excluded"
                  }
                ],
                "result": {
                  "description": "",
                  "id": "abc-def",
                  "results": {
                    "zip": "https://st.icons8.com/zip/abc-def/icons8-font.zip"
                  },
                  "status": "complete",
                  "type": "create_web_font"
                }
              }
            },
            "headers": {},
            "schema": {
              "properties": {
                "messages": {
                  "items": {},
                  "type": "array"
                },
                "result": {
                  "properties": {
                    "description": {
                      "description": "human readable description",
                      "type": "string"
                    },
                    "id": {
                      "description": "task identifier",
                      "type": "string"
                    },
                    "results": {
                      "properties": {
                        "zip": {
                          "type": "string"
                        }
                      },
                      "type": "object"
                    },
                    "status": {
                      "description": "task status",
                      "type": "string"
                    },
                    "type": {
                      "description": "task type",
                      "type": "string"
                    }
                  },
                  "required": [
                    "id",
                    "type",
                    "status"
                  ],
                  "type": "object"
                }
              },
              "type": "object"
            }
          }
        },
        "summary": "From Separate Icons",
        "tags": []
      }
    }
  },
  "definitions": {
    "AuthArgument": {
      "properties": {
        "hash": {
          "type": "string"
        }
      },
      "required": [
        "hash"
      ],
      "type": "object"
    },
    "CategoryV3Item": {
      "properties": {
        "category_code": {
          "type": "string"
        },
        "category_name": {
          "type": "string"
        },
        "subcategory": {
          "items": {},
          "type": "array"
        }
      },
      "type": "object"
    },
    "CollectionWebFontTaskArguments": {
      "properties": {
        "arguments": {
          "type": "object"
        }
      },
      "type": "object"
    },
    "CompactCategoryV3Item": {
      "properties": {
        "api_code": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "api_code"
      ],
      "type": "object"
    },
    "CompactIconV3Item": {
      "properties": {
        "category": {
          "type": "string"
        },
        "common_icon_id": {
          "type": "number"
        },
        "created": {
          "type": "string"
        },
        "features": {
          "type": "object"
        },
        "id": {
          "type": "number"
        },
        "name": {
          "type": "string"
        },
        "platform_code": {
          "type": "string"
        },
        "share": {
          "type": "object"
        },
        "subcategory": {
          "type": "object"
        },
        "svg": {
          "type": "string"
        },
        "url": {
          "type": "string"
        },
        "vector": {
          "type": "object"
        }
      },
      "required": [
        "id",
        "name",
        "platform_code",
        "created",
        "common_icon_id",
        "svg",
        "features"
      ],
      "type": "object"
    },
    "IconV3Item": {
      "$ref": "#/definitions/CompactIconV3Item"
    },
    "Meta": {},
    "Search": {},
    "TaskError": {
      "properties": {
        "code": {
          "enum": [
            "json_not_valid",
            "auth_required",
            "auth_failed",
            "access_denied",
            "io_fail",
            "database_fail",
            "argument_is_missed",
            "argument_is_wrong",
            "paid_feature",
            "not_possible"
          ],
          "type": "string"
        },
        "description": {
          "type": "string"
        }
      },
      "required": [
        "code",
        "description"
      ],
      "type": "object"
    },
    "TaskResult": {
      "properties": {
        "description": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "results": {
          "type": "object"
        },
        "status": {
          "enum": [
            "`preparing+",
            "idle",
            "in_progress",
            "timeout",
            "complete",
            "failed"
          ],
          "type": "string"
        },
        "type": {
          "enum": [
            "create_web_font",
            "create_svg_set"
          ],
          "type": "string"
        }
      },
      "required": [
        "id",
        "type",
        "status"
      ],
      "type": "object"
    },
    "TotalV3Item": {
      "properties": {
        "api_code": {
          "enum": [
            "ios7",
            "win8",
            "win10",
            "android",
            "androidL",
            "color",
            "office"
          ],
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "total": {
          "type": "number"
        }
      },
      "required": [
        "name",
        "api_code",
        "total"
      ],
      "type": "object"
    },
    "Web_Fonts": {}
  }
}
